"""
Setup Script
Automated setup and configuration for the honeytoken system.
"""

import os
import sys
import json
from pathlib import Path


def print_header(text):
    """Print a formatted header."""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60)


def print_step(step_num, text):
    """Print a step."""
    print(f"\n[{step_num}] {text}")


def create_env_file():
    """Create .env file with configuration templates."""
    env_template = """# Honeytoken System Configuration
# Generated by setup script

# GitHub Integration
GITHUB_TOKEN=your_github_token_here

# Email Alerts (Gmail example)
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=your_email@gmail.com
SMTP_PASSWORD=your_app_password_here
SMTP_FROM=your_email@gmail.com
ALERT_EMAIL_TO=security@example.com

# Webhook Configuration
WEBHOOK_URLS=https://example.com/webhook

# Slack Integration (optional)
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/WEBHOOK/URL

# Discord Integration (optional)
DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/YOUR/WEBHOOK/URL

# Microsoft Teams Integration (optional)
TEAMS_WEBHOOK_URL=https://outlook.office.com/webhook/YOUR/WEBHOOK/URL

# Webhook Server
WEBHOOK_SERVER_HOST=0.0.0.0
WEBHOOK_SERVER_PORT=8080

# Application Settings
LOG_LEVEL=INFO
SCAN_ON_STARTUP=false
AUTO_INJECT_HONEYTOKENS=false
"""
    
    env_file = '.env'
    
    if os.path.exists(env_file):
        response = input(f"\n⚠️  {env_file} already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("   Skipping .env creation")
            return False
    
    with open(env_file, 'w') as f:
        f.write(env_template)
    
    print(f"   ✓ Created {env_file}")
    return True


def create_gitignore():
    """Create .gitignore file."""
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual Environment
venv/
env/
ENV/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Sensitive Files
.env
.env.local
.env.production
*.pem
*.key
*.crt

# Honeytoken System Files
honeytokens.json
scan_results.json
alert_history.json
injection_log.json
webhook_events.json

# Logs
*.log
logs/

# OS
.DS_Store
Thumbs.db

# Testing
.pytest_cache/
.coverage
htmlcov/

# Docker
docker-compose.override.yml
"""
    
    gitignore_file = '.gitignore'
    
    if os.path.exists(gitignore_file):
        with open(gitignore_file, 'r') as f:
            existing_content = f.read()
        
        if 'honeytokens.json' in existing_content:
            print(f"   ℹ️  {gitignore_file} already configured")
            return True
        
        # Append to existing
        with open(gitignore_file, 'a') as f:
            f.write("\n# Honeytoken System\n")
            f.write("honeytokens.json\n")
            f.write("scan_results.json\n")
            f.write("alert_history.json\n")
            f.write("injection_log.json\n")
            f.write("webhook_events.json\n")
        
        print(f"   ✓ Updated {gitignore_file}")
    else:
        with open(gitignore_file, 'w') as f:
            f.write(gitignore_content)
        
        print(f"   ✓ Created {gitignore_file}")
    
    return True


def create_directories():
    """Create necessary directories."""
    directories = [
        'logs',
        'reports',
        'data',
        '.github/workflows'
    ]
    
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
        print(f"   ✓ Created directory: {directory}")
    
    return True


def validate_env_file():
    """Validate .env file configuration."""
    if not os.path.exists('.env'):
        print("   ⚠️  .env file not found")
        return False
    
    required_vars = [
        'GITHUB_TOKEN',
        'SMTP_SERVER',
        'SMTP_PORT'
    ]
    
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        missing = []
        for var in required_vars:
            value = os.getenv(var)
            if not value or 'your_' in value.lower() or 'example' in value.lower():
                missing.append(var)
        
        if missing:
            print(f"   ⚠️  Please configure these variables in .env:")
            for var in missing:
                print(f"      - {var}")
            return False
        
        print("   ✓ Environment variables validated")
        return True
    
    except ImportError:
        print("   ℹ️  python-dotenv not installed, skipping validation")
        return True


def check_dependencies():
    """Check if required dependencies are installed."""
    required_packages = {
        'requests': 'requests',
        'dotenv': 'python-dotenv',
    }
    
    optional_packages = {
        'nacl': 'PyNaCl (for GitHub secrets)',
    }
    
    print("\n   Checking required packages:")
    all_installed = True
    
    for module, package in required_packages.items():
        try:
            __import__(module)
            print(f"      ✓ {package}")
        except ImportError:
            print(f"      ✗ {package} - MISSING")
            all_installed = False
    
    print("\n   Checking optional packages:")
    for module, package in optional_packages.items():
        try:
            __import__(module)
            print(f"      ✓ {package}")
        except ImportError:
            print(f"      ○ {package} - not installed (optional)")
    
    if not all_installed:
        print("\n   ⚠️  Install missing packages: pip install -r requirements.txt")
        return False
    
    return True


def initialize_data_files():
    """Initialize JSON data files."""
    data_files = {
        'honeytokens.json': {'tokens': []},
        'scan_results.json': {'scans': []},
        'alert_history.json': {'alerts': []},
        'injection_log.json': {'injections': []},
        'webhook_events.json': {'events': []},
        'alert_config.json': {
            'email': {'enabled': False},
            'webhook': {'enabled': False},
            'slack': {'enabled': False}
        }
    }
    
    for filename, initial_data in data_files.items():
        if not os.path.exists(filename):
            with open(filename, 'w') as f:
                json.dump(initial_data, f, indent=2)
            print(f"   ✓ Created {filename}")
        else:
            print(f"   ℹ️  {filename} already exists")
    
    return True


def test_modules():
    """Test if all modules can be imported."""
    modules = [
        'honeytoken_generator',
        'token_scanner',
        'github_integration',
        'alert_system',
        'webhook_server',
        'honeytoken_injector',
        'ci_scanner'
    ]
    
    print("\n   Testing module imports:")
    all_ok = True
    
    for module in modules:
        try:
            __import__(module)
            print(f"      ✓ {module}")
        except ImportError as e:
            print(f"      ✗ {module} - Error: {e}")
            all_ok = False
    
    return all_ok


def display_next_steps():
    """Display next steps for the user."""
    print_header("Setup Complete!")
    
    print("""
Next Steps:

1. Configure .env file:
   - Add your GitHub token
   - Configure email settings (for alerts)
   - Add webhook URLs (optional)

2. Generate honeytokens:
   python honeytoken_generator.py --type github_pat --count 5

3. Inject honeytokens into a test repository:
   python honeytoken_injector.py --inject-repo ./test-repo

4. Start the webhook server:
   python webhook_server.py --port 8080

5. Run a scan:
   python token_scanner.py ./your-repository

6. Test alerts:
   python alert_system.py --test-email

7. Use in CI/CD:
   - See .github/workflows/honeytoken-detection.yml for GitHub Actions
   - Or run: python ci_scanner.py --scan-workspace

8. View the dashboard:
   - Open dashboard.html in your browser

For more information, see IMPLEMENTATION_GUIDE.txt
""")


def main():
    """Main setup process."""
    print_header("Honeytoken System Setup")
    
    print("""
This script will set up the honeytoken detection system:
  ✓ Create configuration files
  ✓ Set up directory structure
  ✓ Initialize data files
  ✓ Validate dependencies
""")
    
    response = input("\nContinue with setup? (Y/n): ")
    if response.lower() == 'n':
        print("Setup cancelled")
        sys.exit(0)
    
    # Step 1: Create .env file
    print_step(1, "Creating .env configuration file")
    create_env_file()
    
    # Step 2: Create .gitignore
    print_step(2, "Creating/updating .gitignore")
    create_gitignore()
    
    # Step 3: Create directories
    print_step(3, "Creating directory structure")
    create_directories()
    
    # Step 4: Initialize data files
    print_step(4, "Initializing data files")
    initialize_data_files()
    
    # Step 5: Check dependencies
    print_step(5, "Checking dependencies")
    deps_ok = check_dependencies()
    
    if not deps_ok:
        print("\n⚠️  Please install dependencies before continuing:")
        print("   pip install -r requirements.txt")
    
    # Step 6: Test module imports
    print_step(6, "Testing module imports")
    modules_ok = test_modules()
    
    if not modules_ok:
        print("\n⚠️  Some modules failed to import. Check errors above.")
    
    # Step 7: Validate environment
    print_step(7, "Validating environment configuration")
    validate_env_file()
    
    # Display next steps
    display_next_steps()
    
    # Final status
    if deps_ok and modules_ok:
        print("\n✅ Setup completed successfully!\n")
        sys.exit(0)
    else:
        print("\n⚠️  Setup completed with warnings. See messages above.\n")
        sys.exit(1)


if __name__ == '__main__':
    main()
